name: docs

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  docs_branch: gh-pages
  docs_src_path: docs_src
  docs_build_path: docs_src/_build
  docs_path: docs
  sphinx_builder: dirhtml

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.docs_branch}}
          # We push new commits onto the docs branch here after merging main into it
          # (including possibly 1 merge commit). If we run this workflow several times
          # without any new commits from main, the docs branch can have arbitrarily many
          # commits ahead of main. We need common commits between the docs branch and
          # main in order to merge them, so it's best to just fetch the whole history.
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Configure git
        run: |
          git config user.name 'GitHub CI'
          git config user.email ''
      - name: Merge main into pages branch
        run: |
          echo "++++++++++++++ git status +++++++++++++++" && git status
          echo "++++++++++++++ git branch +++++++++++++++" && git branch
          echo "++++++++++++++ git branch all +++++++++++++++" && git branch -a
          echo "++++++++++++++ git log current +++++++++++++++" && git --no-pager log -n 20
          echo "++++++++++++++ git log origin/main +++++++++++++++" && git --no-pager log -n 20 origin/main
          echo "++++++++++++++ git log origin/gh-pages +++++++++++++++" && git --no-pager log -n 20 origin/gh-pages
          echo "+++++++++++++++++++ git fetch origin +++++++++++++++++++" && git fetch origin
          echo "++++++++++++++ git status +++++++++++++++" && git status
          echo "++++++++++++++ git branch +++++++++++++++" && git branch
          echo "++++++++++++++ git branch all +++++++++++++++" && git branch -a
          echo "++++++++++++++ git log current +++++++++++++++" && git --no-pager log -n 20
          echo "++++++++++++++ git log origin/main +++++++++++++++" && git --no-pager log -n 20 origin/main
          echo "++++++++++++++ git log origin/gh-pages +++++++++++++++" && git --no-pager log -n 20 origin/gh-pages
          echo "+++++++++++++++++++ git merge origin/main +++++++++++++++++++" && git merge origin/main
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]
      - name: Move docs to build path
        run: |
          mkdir -p ${{env.docs_path}}
          mkdir -p ${{env.docs_build_path}}
          mv ${{env.docs_path}} ${{env.docs_build_path}}/${{env.sphinx_builder}}
      - name: Run sphinx
        run: |
          cd ${{env.docs_src_path}}
          make ${{env.sphinx_builder}}
      - name: Move docs to published path
        run: |
          mv ${{env.docs_build_path}}/${{env.sphinx_builder}} ${{env.docs_path}}
      - name: Push changes to docs and build dirs
        run: |
          git add -f ${{env.docs_path}} ${{env.docs_build_path}}
          git commit -m "(CI:) Update docs from workflow ${{github.workflow}} (run ${{github.run_id}})."
          git push
