name: publish

on:
  workflow_dispatch:
    inputs:
      package_index:
        description: 'Where to publish (pypi or testpypi)'
        required: true
        default: 'pypi'
        
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build dist archives
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        python -m build
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: ${{github.event.inputs.package_index == 'pypi'}}
      with:
        user: __token__
        password: ${{secrets.PYPI_API_TOKEN}}
        repository_url: 'https://upload.pypi.org/legacy/'
    - name: Upload to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: ${{github.event.inputs.package_index == 'testpypi'}}
      with:
        user: __token__
        password: ${{secrets.TEST_PYPI_API_TOKEN}}
        repository_url: 'https://test.pypi.org/legacy/'
