name: publish

on:
  workflow_dispatch:
    inputs:
      api_token:
        description: 'API Token (from https://pypi.org/manage/account/#api-tokens)'     
        required: true
      package_index:
        description: 'Where to publish (https://upload.pypi.org/legacy/ or https://test.pypi.org/legacy/)'
        required: true
        default: 'https://upload.pypi.org/legacy/'

jobs:
  publish_to_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build dist archives
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        python -m build
    - name: Upload
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{github.event.inputs.api_token}}
        repository_url: ${{github.event.inputs.package_index}}
