name: tests+coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests]
        pip install .[coverage]
    - name: Tests and coverage
      run: |
        coverage erase
        coverage run --parallel-mode --branch --source=nx_config --omit=**/__init__.py -m unittest discover -v -s tests/
    - name: Upload coverage data
      uses: actions/upload-artifact@v2
      with:
        name: .cov
        path: .coverage.*
        retention-days: 1
  combined_coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download coverage for individual python versions
      uses: actions/download-artifact@v2
      id: dl_cov_parts
      with:
        name: .cov
        path: .cov
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Combine coverage
      run: |
        python -m pip install --upgrade pip
        pip install .[coverage]
        coverage combine ${{steps.dl_cov_parts.outputs.download-path}}
        coverage json
    - name: Upload coverage JSON
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage.json
    - name: Report and update stats
      run: |
        echo ${GITHUB_WORKFLOW}
        echo ${GITHUB_RUN_ID}
        python .github/workflows/report_and_update_stats.py \
          --workflow=${GITHUB_WORKFLOW} --run-id=${GITHUB_RUN_ID} --min-coverage=100.0
        ls -la .github/workflows
        cat .github/workflows/.${GITHUB_WORKFLOW}.stats.latest.json
