name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests]
        pip install .[coverage]
    - name: Tests and coverage
      run: |
        coverage erase
        coverage run --branch --source=nx_config --omit=**/__init__.py -m unittest discover -v -s tests/
        coverage json
        coverage report
    - name: Upload coverage data
      uses: actions/upload-artifact@v2
      with:
        name: .coverage.${{ matrix.python-version }}
        path: .coverage
    - name: Upload coverage JSON
      uses: actions/upload-artifact@v2
      with:
        name: coverage.${{ matrix.python-version }}.json
        path: coverage.json
  combined_coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download coverage for individual python versions
      uses: actions/download-artifact@v2
    - name: Combine coverage
      run: |
        python -m pip install --upgrade pip
        pip install .[coverage]
        coverage combine
        coverage json
        coverage report
    - name: Upload coverage JSON
      uses: actions/upload-artifact@v2
      with:
        name: coverage.combined.json
        path: coverage.json
